name: E-Learning DBaaS Test

on: [push]

jobs:
  test-dbaas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup database
        run: |
          python -c "from database import init_db; init_db()"
          echo "Database setup complete."

      - name: Run app and test endpoints
        run: |
          python app.py &
          sleep 5
          curl http://127.0.0.1:8080/
          curl http://127.0.0.1:8080/students
          curl http://127.0.0.1:8080/courses
          curl http://127.0.0.1:8080/enrollments
